import { useId, useState } from 'react';
import { Type, Heart, Image, LayoutGrid, Calendar, Infinity, Star, Plus, ChevronDown, AlignLeft, AlignCenter, AlignRight, Minus, SlidersHorizontal, Orbit, MousePointer2 } from 'lucide-react';
import { FONTS, normalizeDesign, outsideZone } from '../../engraving/design';
const symbols = ['♥', '♡', '∞', '★', '✦', '🐾', '♛', '☾', '✿', '❀', '☺', '☀', '⚓', '✝', '💍', '🎂', '😊', '🌙'];
const mono = (text) => text.replace(/\uFE0F/g, '');
const count = (text) => typeof Intl.Segmenter === 'function' ? [...new Intl.Segmenter('sr', { granularity: 'grapheme' }).segment(text)].length : Array.from(text).length;
const fonts = [['serif', false, 'Klasični'], ['sans', false, 'Moderni'], ['serif', true, 'Elegantni'], ['hand', false, 'Rukopis'], ['mono', false, 'Mono']];
export function Stepper({ label, value, suffix = '', min, max, step = 1, onChange, disabled }) {
  const update = (number) => { if (Number.isFinite(number)) onChange(Number(Math.max(min, Math.min(max, number)).toFixed(2))); };
  return <label className="engrave-stepper"><span>{label}</span><div><button disabled={disabled || value <= min} aria-label={`Smanji: ${label}`} onClick={() => update(value - step)}><Minus size={16} /></button><span className="engrave-stepper-value"><input aria-label={label} type="number" min={min} max={max} step={step} disabled={disabled} value={value} onChange={(e) => update(e.target.valueAsNumber)} />{suffix && <small>{suffix}</small>}</span><button disabled={disabled || value >= max} aria-label={`Povećaj: ${label}`} onClick={() => update(value + step)}><Plus size={16} /></button></div></label>;
}
export default function SimpleControls({ layer, patch, addText, addSymbol, onDelete, upload, template, layers, selected, selectLayer, duplicate, reorder, toggleLock }) {
  const [tab, setTab] = useState('text'); const [moreSymbols, setMoreSymbols] = useState(false); const [allFonts, setAllFonts] = useState(false); const [suggestions, setSuggestions] = useState(false); const arcId = useId().replace(/:/g, '');
  const image = layer?.type === 'image'; const disabled = !layer || layer.locked;
  const text = image ? '' : mono(layer?.text || '');
  const write = (value) => {
    const nextText = mono(value); if (count(nextText) > 40 || nextText.split('\n').length > 3) return;
    if (!layer || image) { addText(nextText); return; }
    let next = { ...layer, text: nextText };
    while (next.fontSize > 14 && outsideZone(normalizeDesign({ layers: [next] }).layers[0])) next.fontSize--;
    patch({ text: nextText, fontSize: next.fontSize });
  };
  const symbolPanel = <details className="engrave-option-panel engrave-symbol-panel" open><summary><span><Orbit size={18} />Simboli / emoji</span><small>Svi simboli i emoji graviraju se jednobojno.</small><ChevronDown size={16} /></summary><div className="engrave-symbols">{symbols.slice(0, moreSymbols ? symbols.length : 11).map((symbol) => <button key={symbol} disabled={layer?.locked} aria-label={`Dodaj simbol ${symbol}`} onClick={() => image || !layer ? addSymbol(symbol) : write(text + symbol)}>{mono(symbol)}</button>)}<button className="engrave-more" onClick={() => setMoreSymbols(!moreSymbols)}>Još <ChevronDown size={14} /></button></div></details>;
  const controls = (key, label, min, max, step = 1, suffix = '') => <Stepper label={label} value={layer?.[key] ?? min} min={min} max={max} step={step} suffix={suffix} disabled={disabled} onChange={(value) => patch({ [key]: value })} />;
  return <div className="engrave-editor">
    <div className="engrave-tabs" role="tablist" aria-label="Sadržaj gravure">{[['text', Type, 'Tekst'], ['symbols', Heart, 'Simboli'], ['image', Image, 'Slika / logo'], ['templates', LayoutGrid, 'Predlošci']].map(([key, Icon, title]) => <button key={key} role="tab" id={`engrave-tab-${key}`} aria-selected={tab === key} aria-controls={`engrave-panel-${key}`} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}><Icon size={23} /><span>{title}</span></button>)}</div>
    <div role="tabpanel" id={`engrave-panel-${tab}`} aria-labelledby={`engrave-tab-${tab}`}>
      {tab === 'text' && <>
        <label className="engrave-message"><span><b>Unesite tekst <em>(do 3 reda / 40 karaktera)</em></b><small>{count(text)} / 40</small></span><textarea aria-label="Tekst za graviranje" placeholder={'12. 10. 2026.\nNaš dan ♥'} disabled={layer?.locked} value={text} onChange={(e) => write(e.target.value)} /></label>
        <div className="engrave-suggestions">{[[Calendar, 'Datum', new Date().toLocaleDateString('sr-RS')], [Heart, 'Naš dan', 'Naš dan ♥'], [Infinity, 'Uvek zajedno', '♥ UVEK ZAJEDNO ♥'], [Star, 'Za uvek', 'Za uvek']].map(([Icon, title, value]) => <button key={title} disabled={layer?.locked} onClick={() => write(value)}><Icon size={18} />{title}</button>)}<button onClick={() => setSuggestions(!suggestions)}><Plus size={17} />Još predloga<ChevronDown size={14} /></button></div>
        {suggestions && <div className="engrave-suggestions engrave-extra-suggestions">{['S ljubavlju', 'Samo za tebe', 'Čuvam te u srcu', 'Naša priča traje', 'Hvala što postojiš'].map((value) => <button key={value} disabled={layer?.locked} onClick={() => write(value)}>{value}</button>)}</div>}
        <div className="engrave-section-label"><b>Font</b><button onClick={() => setAllFonts(!allFonts)}>{allFonts ? 'Prikaži manje' : 'Pogledaj sve'}<ChevronDown size={14} /></button></div>
        <div className="engrave-fonts">{[...fonts, ...(allFonts ? [['sans', true, 'Moderni italic'], ['mono', true, 'Mono italic'], ['hand', true, 'Rukopis italic']] : [])].map(([font, italic, title]) => <button key={title} disabled={disabled || image} aria-pressed={layer?.font === font && Boolean(layer?.italic) === italic} className={layer?.font === font && Boolean(layer?.italic) === italic ? 'active' : ''} onClick={() => patch({ font, italic })}><span style={{ fontFamily: `"${FONTS[font]}", "Gravura Emoji"`, fontStyle: italic ? 'italic' : 'normal' }}>{text || '12. 10. 2026.\nNaš dan ♥'}</span><small>{title}</small></button>)}</div>
        <div className="engrave-format-row"><div><b>Poravnanje</b><div className="engrave-tile-row">{[['left', AlignLeft, 'Levo'], ['center', AlignCenter, 'Sredina'], ['right', AlignRight, 'Desno']].map(([align, Icon, title]) => <button key={align} disabled={disabled || image} className={layer?.align === align ? 'active' : ''} aria-pressed={layer?.align === align} onClick={() => patch({ align })}><Icon size={18} />{title}</button>)}</div></div><div><b>Putanja teksta</b><div className="engrave-tile-row">{[['straight', '≡', 'Prav tekst'], ['upper', '⌒', 'Gornji luk'], ['lower', '⌣', 'Donji luk'], ['circle', '◌', 'Puni krug']].map(([curve, icon, title]) => <button key={curve} disabled={disabled || image} className={layer?.curve === curve ? 'active' : ''} aria-pressed={layer?.curve === curve} onClick={() => patch({ curve, ...(curve !== 'straight' && layer.curve === 'straight' ? { x: 500, y: 500, radius: 266, angle: 0 } : {}) })}><span className="engrave-path-icon">{icon}</span>{title}</button>)}</div></div></div>
        {!image && layer?.curve !== 'straight' && layer && <details className="engrave-option-panel" open><summary><span><Orbit size={18} />Podešavanja luka</span><ChevronDown size={16} /></summary><div className="engrave-arc-controls"><Stepper label="Radijus luka" value={Math.round(layer.radius / 380 * 100)} suffix="%" min={22} max={100} disabled={disabled} onChange={(percent) => patch({ radius: Math.round(percent / 100 * 380) })} />{controls('angle', 'Početni ugao', -180, 180, 1, '°')}<svg className="engrave-arc-example" viewBox="0 0 200 90" aria-label="Pregled zakrivljenosti"><path id={arcId} d={layer.curve === 'lower' ? 'M 20 20 Q 100 110 180 20' : 'M 20 80 Q 100 -15 180 80'} fill="none" stroke="#8fa9ee" strokeDasharray="4 4" /><text fontSize="13" fontFamily={`"${FONTS[layer.font]}", "Gravura Emoji"`} fill="#424958"><textPath href={`#${arcId}`} startOffset="50%" textAnchor="middle">{text || 'UVEK ZAJEDNO'}</textPath></text><circle cx="20" cy={layer.curve === 'lower' ? 20 : 80} r="4" fill="#596071" /><circle cx="180" cy={layer.curve === 'lower' ? 20 : 80} r="4" fill="#596071" /></svg></div></details>}
        {symbolPanel}
      </>}
      {tab === 'symbols' && <><p className="engrave-note">Izaberite simbol za svoju poruku. Emoji se prikazuju i graviraju u jednoj boji.</p>{symbolPanel}</>}
      {tab === 'image' && <div className="engrave-image-controls"><label className="engrave-upload"><Image size={25} /><b>Dodajte sliku ili logo</b><span>PNG, JPEG ili WebP do 10 MB</span><input type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={upload} /></label><p className="engrave-note">Slika se automatski pretvara u jednobojnu gravuru.</p>{image && <><div className="engrave-stepper-grid"><Stepper label="Širina slike" value={Math.round(layer.width)} min={30} max={600} disabled={disabled} onChange={(width) => patch({ width, height: layer.height * width / layer.width })} />{controls('contrast', 'Kontrast', .5, 3, .1)}{controls('threshold', 'Prag crne boje', 0, 255)}</div><label className="engrave-invert"><input type="checkbox" disabled={disabled} checked={layer.invert} onChange={(e) => patch({ invert: e.target.checked })} />Invertuj sliku</label></>}</div>}
      {tab === 'templates' && <><div className="engrave-template-grid">{[['date', '12. 10. 2026.', 'Naš dan ♥', 'Važan datum'], ['circle', '♥ UVEK ZAJEDNO ♥', 'Naš dan ♥', 'Uvek zajedno'], ['love', 'Za najlepše trenutke', 'S ljubavlju', 'Posveta']].map(([kind, first, second, title]) => <button key={kind} onClick={() => { template(kind); setTab('text'); }}><span>{first}</span><i>{second}</i><b>{title}</b></button>)}</div><p className="engrave-note">Predložak zamenjuje dizajn. Promenu možete poništiti.</p></>}
    </div>
    {layer && <details className="engrave-option-panel engrave-advanced" open><summary><span><SlidersHorizontal size={18} />Napredna podešavanja</span><ChevronDown size={16} /></summary><div className="engrave-stepper-grid">{image ? <Stepper label="Veličina slike" value={Math.round(layer.width)} min={30} max={600} disabled={disabled} onChange={(width) => patch({ width, height: layer.height * width / layer.width })} /> : <>{controls('fontSize', 'Veličina teksta', 14, 100)}{controls('letterSpacing', 'Razmak slova', -2, 15, .5)}{controls('lineSpacing', 'Razmak redova', 1, 2.5, .1)}</>}</div><div className="engrave-advanced-tools"><button disabled={disabled} onClick={() => patch({ x: 500, y: 500 })}><MousePointer2 size={15} />Centriraj</button>{!image && <><button disabled={disabled} aria-pressed={layer.bold} className={layer.bold ? 'active' : ''} onClick={() => patch({ bold: !layer.bold })}><b>B</b></button><button disabled={disabled} aria-pressed={layer.italic} className={layer.italic ? 'active' : ''} onClick={() => patch({ italic: !layer.italic })}><i>I</i></button></>}<button disabled={disabled} onClick={duplicate}>Dupliraj</button><button disabled={disabled} onClick={onDelete}>Obriši</button><button onClick={toggleLock}>{layer.locked ? 'Otključaj' : 'Zaključaj'}</button></div><div className="engrave-stepper-grid">{controls('x', 'Položaj X', 0, 1000)}{controls('y', 'Položaj Y', 0, 1000)}{controls('rotation', 'Rotacija', -180, 180, 1, '°')}{!image && layer.curve !== 'straight' && controls('arc', 'Širina luka', 30, 330, 1, '°')}</div><div className="engrave-layer-list">{layers.map((item, index) => <button key={item.id} className={selected === item.id ? 'active' : ''} onClick={() => selectLayer(item.id)}>{item.locked ? '🔒 ' : ''}{item.type === 'text' ? item.text || `Poruka ${index + 1}` : 'Slika / logo'}</button>)}</div><div className="engrave-advanced-tools"><button disabled={disabled || layers.findIndex((item) => item.id === selected) === layers.length - 1} onClick={() => reorder(1)}>Sloj napred ↑</button><button disabled={disabled || layers.findIndex((item) => item.id === selected) === 0} onClick={() => reorder(-1)}>Sloj nazad ↓</button><button onClick={() => addText('')}>＋ Još jedna poruka</button></div>{layer.locked && <p className="engrave-note">Otključajte element za uređivanje.</p>}</details>}
  </div>;
}