export const seoConfig = {
  siteUrl: import.meta.env.VITE_SITE_URL || '',
  siteName: import.meta.env.VITE_SITE_NAME || 'DajaShop',
  siteDescription: import.meta.env.VITE_SITE_DESCRIPTION || '',
  siteKeywords: import.meta.env.VITE_SITE_KEYWORDS || '',
  siteLocale: import.meta.env.VITE_SITE_LOCALE || 'sr_RS',
  siteLocaleAlt: import.meta.env.VITE_SITE_LOCALE_ALT || '',
  ogDefaultImage: import.meta.env.VITE_OG_DEFAULT_IMAGE || '',
  twitterHandle: import.meta.env.VITE_TWITTER_HANDLE || '',
  facebookAppId: import.meta.env.VITE_FACEBOOK_APP_ID || '',
  siteLogoUrl: import.meta.env.VITE_SITE_LOGO_URL || '',
  googleSiteVerification: import.meta.env.VITE_GOOGLE_SITE_VERIFICATION || '',
  business: {
    name: import.meta.env.VITE_BUSINESS_NAME || '',
    street: import.meta.env.VITE_BUSINESS_STREET || '',
    city: import.meta.env.VITE_BUSINESS_CITY || '',
    postalCode: import.meta.env.VITE_BUSINESS_POSTAL_CODE || '',
    country: import.meta.env.VITE_BUSINESS_COUNTRY || 'RS',
    phone: import.meta.env.VITE_BUSINESS_PHONE || '',
    email: import.meta.env.VITE_BUSINESS_EMAIL || '',
    hours: import.meta.env.VITE_BUSINESS_HOURS || '',
  },
};
